controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation


about:

    path: /about

    controller: App\Controller\DefaultController::about


index:
    path: /
    controller: App\Controller\MovieController::myindex
   

delete:

    path: /movies/delete/{id}

    controller: App\Controller\MovieController::delete








